'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
'''
# Answer = 4613732

# Seed values
cur_term = 2
prev_term = 1
total_even = 2

while cur_term < 4000000:
    temp = cur_term
    cur_term = temp + prev_term
    prev_term = temp

    if cur_term % 2 == 0:
        total_even += cur_term

print(total_even)
